### PR TITLE
Swift4

### PR DESCRIPTION
**Pull request by tuken**

### CODE REVIEW

**Comment by noppoMan** [comment]
@tuken 
Thanks for your great PR!
But the test seems to run with Swift 3.1, So it's failed to parse Package.swift.
Could you update .travis.yml to use Swift4?

**Comment by noppoMan** [comment]
And one more.

I'll replace Mysql Module from under `Sources/Mysql` to https://github.com/noppoMan/SwiftMysql. After merging this PR.(It have already supported Swift4)

**Comment by tuken24** [comment]
i fixed it. the test run correctly.

**Comment by noppoMan** [comment]
LGTM thanks!
merging

**Comment by noppoMan** [comment]
I published version 0.3.0 for Swift 4
https://github.com/noppoMan/SwiftKnex/releases/tag/0.3.0

**Pull request merged**
